
path: /Users/kporeba6311/Documents/GitHub/ABB_OPENCV/objDetection/trainingData/annotated_data
train: /Users/kporeba6311/Documents/GitHub/ABB_OPENCV/objDetection/trainingData/annotated_data/obj_train_data/images/train
val: /Users/kporeba6311/Documents/GitHub/ABB_OPENCV/objDetection/trainingData/annotated_data/obj_train_data/images/train


# Classes
names:
  0: Cylinder