
path: G:\GithubRepos\ABB_OPENCV\objDetection\trainingData\annotated_data_2
train: G:\GithubRepos\ABB_OPENCV\objDetection\trainingData\annotated_data_2\obj_Train_data\images\train
val: G:\GithubRepos\ABB_OPENCV\objDetection\trainingData\annotated_data_2\obj_Train_data\images\train


# Classes
names:
  0: Cylinder