
path: /Users/kporeba6311/Documents/GitHub/ABB_OPENCV/objDetection/trainingData/annotated_data_2
train: /Users/kporeba6311/Documents/GitHub/ABB_OPENCV/objDetection/trainingData/annotated_data/obj_train_data/images
val: /Users/kporeba6311/Documents/GitHub/ABB_OPENCV/objDetection/trainingData/annotated_data/obj_train_data/images


# Classes
names:
  0: Cylinder